### ISSUE TITLE
A failed test configuration in the connection settings produces [object object] as the error

### ISSUE THREAD

**Issue by KamranVahdati** [OneIdentity/SafeguardDevOpsService#214]
In the 1.6.0.49496 prerelease when you fail a test configuration for a vault, the UI reports the error [object, object]

![object object](https://user-images.githubusercontent.com/13633790/115630892-0ff4f900-a2c2-11eb-9694-2d85595fe689.PNG)

**Comment by bnicholesdell** [comment]
Fixed in 1.6.0.50164
