### ISSUE TITLE
Error" Certificate is expired although it is valid

### ISSUE THREAD

**Issue by VVargaOI** [OneIdentity/SafeguardDevOpsService#348]
Hi,

When configuring the Secrets Broker I need to upload a certificate which will then be configured as the client certificate of the Broker to authenticate against SPP.
Regardless of uploading a standard TLS client PFX or a PEM generated upon signing the CSR from the Broker, the Broker threw the "Certificate is expired" error message. All the certificates were shown valid when opened in external certificate management software / Windows certificate store.
I'm wondering if extending the[ respective code](https://github.com/OneIdentity/SafeguardDevOpsService/blob/1d3665a7a08fd9861594818202316fd48b41fdc6/SafeguardDevOpsService/Logic/CertificateHelper.cs#L170) with some debug logs may help to investigate similar issues in the future, like logging out curDate, sslCertificate.NotBefore and sslCertificate.NotAfter.

For reference: after a while one of the certificates (the first one I generated during my config attempts) started to work, which makes me to suspect there could have been some timezone other time related issue.

Thanks!
Viktor

**Comment by bnicholesdell** [comment]
Fixed in PR https://github.com/OneIdentity/SafeguardDevOpsService/pull/373
