### ISSUE TITLE
Initialize-SecretsBrokerForHashiCorp.ps1 - Errors due to missing fields that do not exist in SPP v.7.0.2 LTS

### ISSUE THREAD

**Issue by baffledmystic** [OneIdentity/SafeguardDevOpsService#390]
PS script uses "$local:MappedAssetAccountObj.SystemName" to point to an asset in SPP

But, from what I can tell, there's no field titled "SystemName" in the AssetAccountObject
I modified the script to use:
 -Asset **$local:MappedAssetAccountObj.Asset.Name**
 
Many other modifications felt needed for the script to work as expected.
 
Shounak S.
IKEA IT AB

**Comment by bnicholesdell** [comment]
This issue will be fixed by pull request, https://github.com/OneIdentity/SafeguardDevOpsService/pull/392 once it is merged to master.

**Comment by bnicholesdell** [comment]
Merge done
