### ISSUE TITLE
Canceling the edit plugin side sheet mixed up the plugin cards on the main screen

### ISSUE THREAD

**Issue by bnicholesdell** [OneIdentity/SafeguardDevOpsService#407]
Canceling the plugin edit side sheet when it is currently looking at an instance of a plugin, causes issues with the plugin cards on the main screen.

    Install 2 or more plugins
    Create 2 or more instances of each plugin
    Edit the second plugin that is displayed on the main screen
    Scroll to an instance of the plugin which isn't the root instance.
    Cancel the edit side sheet.

At this point you can't click on the Edit Configuration button of the first plugin card on the main screen.  It seems to be disabled. 

    Edit the second plugin again by clicking on the Edit Configuration button.
    Scroll to a different instance.
    Cancel the side sheet.

At this point the first plugin card on the main screen assumes the name and displayed data of the second plugin card.

**Comment by LesWardwell** [comment]
https://github.com/OneIdentity/SafeguardDevOpsService/pull/408
